stages:
  - build
  - test
  - deliver
  - deploy

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      when: always

test:
  stage: test
  script:
    - docker run -d --name test-container -p 8000:8000 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - sleep 10
    - docker ps
    - curl http://localhost:8000
    - docker stop test-container
    - docker rm test-container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      when: always

deliver:
  stage: deliver
  script:
    - docker run -d --name deliver-container -p 8000:8000 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - sleep 10
    - docker ps
    - curl http://localhost:8000
    - docker stop deliver-container
    - docker rm deliver-container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      when: always

deploy:
  stage: deploy
  script:
    - docker run -d --name deploy-container -p 8000:8000 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - sleep 10
    - docker ps
    - curl http://localhost:8000
    - docker stop deploy-container
    - docker rm deploy-container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
