stages:
  - test
  - build
  - deploy


variables:
  IMAGE_NAME: $ECR_REGISTRY/devops-erenduyuk-pyeditorial
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA


test:
  stage: test
  script:
    - echo "test"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      when: always

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add aws-cli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      when: always
  when: manual


deploy:
  stage: deploy
  script:
    - echo "deploy"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
