stages:
  - test
  - build
  - deploy


variables:
  IMAGE_NAME: $ECR_REGISTRY/devops-erenduyuk-pyeditorial
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA


test:
  stage: test
  image: python:3.9.19-slim
  script:
    - echo "test"
  allow_failure: false

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add aws-cli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  allow_failure: false


deploy_test:
  stage: deploy
  image: ubuntu
  script:
    - echo "deploy"
    - apt install ansible -y
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod +x ./ansible/dynamic_inventory.sh
    - ./ansible/dynamic_inventory.sh > ./ansible/inventory.ini
    - ansible-playbook -i ./ansible/inventory.ini ./ansible/deploy_test.yml

deploy_prod:
  stage: deploy
  image: ubuntu
  script:
    - echo "deploy"
    - apt install ansible -y
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod +x ./ansible/dynamic_inventory.sh
    - ./ansible/dynamic_inventory.sh > ./ansible/inventory.ini
    - ansible-playbook -i ./ansible/inventory.ini ./ansible/deploy_prod.yml



