- name: Deploy application to production servers
  hosts: production
  serial: 1
  become: yes
  tasks:
    - name: Stop running container
      shell: "docker stop {{ inventory_hostname }}"
      ignore_errors: yes

    - name: Remove container
      shell: "docker rm {{ inventory_hostname }}"
      ignore_errors: yes

    - name: Remove all Docker images
      shell: "docker rmi {{ inventory_hostname }}"
      ignore_errors: yes

    - name: Pull the latest Docker image
      shell: "docker pull {{ lookup('env', 'IMAGE_NAME') }}:{{ lookup('env', 'IMAGE_TAG') }}"
      when: login_result is succeeded

    - name: List Docker images
      shell: "docker images"
      when: login_result is succeeded

    - name: Run the new Docker container
      shell: "docker run -d --name {{ inventory_hostname }} -p 80:8000 -e DJANGO_ALLOWED_HOSTS={{ ansible_default_ipv4.address }} {{ lookup('env', 'IMAGE_NAME') }}:{{ lookup('env', 'IMAGE_TAG') }}"
      when: login_result is succeeded